plugins { id 'com.android.application' }

android {
    namespace 'in.qrstaff.manager'
    compileSdk 35
    defaultConfig {
        applicationId 'in.qrstaff.manager'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
    buildTypes {
        release { minifyEnabled false }
    }
}
